project_id = "fzgjmvxtgrlwrluxdwjq"

[functions.get-donation-receipt]
verify_jwt = false

[functions.r2-upload]
verify_jwt = false

[functions.migrate-to-r2]
verify_jwt = false

[functions.angel-voice-elevenlabs]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.angel-chat]
verify_jwt = false

[functions.angel-voice]
verify_jwt = false

[functions.update-reward-config]
verify_jwt = false

[functions.og-meta]
verify_jwt = false

[functions.prerender]
verify_jwt = false

[functions.claim-camly]
verify_jwt = false

[functions.award-camly]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.admin-wallet-balance]
verify_jwt = false

[functions.angel-ai-proxy]
verify_jwt = false

[functions.check-upload-reward]
verify_jwt = false

[functions.detect-abuse]
verify_jwt = false

[functions.generate-video-thumbnails]
verify_jwt = false

[functions.search-users-by-email]
verify_jwt = false

[functions.generate-suno-music]
verify_jwt = false

[functions.generate-suno-music-callback]
verify_jwt = false

[functions.generate-lyrics]
verify_jwt = false

[functions.download-ai-music]
verify_jwt = false
